enum BDP_Modifiers
{
	Modifier_StayFrosty		= 1 << 0,
	Modifier_Chatterbox		= 1 << 1,
	Modifier_Triathlon		= 1 << 2,
	Modifier_OneUpmanship	= 1 << 3,
	Modifier_UltraNightmare	= 1 << 4,
	Modifier_SkullCrusher	= 1 << 5,
	Modifier_ScoreMaster	= 1 << 6,
	Modifier_ShockFactor	= 1 << 7,
	Modifier_PerfectHatred	= 1 << 8,
	Modifier_Realism		= 1 << 9,
	Modifier_Gunslinger		= 1 << 10,
	Modifier_SequenceBreak	= 1 << 11,
	Modifier_Fragger		= 1 << 12,
	Modifier_Gluttony		= 1 << 13,
	Modifier_KickInTheHead	= 1 << 14
}

class BDP_ModifierStayFrosty : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "STFROST";
		BDP_Modifier.DisplayName "Stay Frosty";
		BDP_Modifier.Description "Athletic actions require Stamina";
		BDP_Modifier.ModifierID Modifier_StayFrosty;
	}
}

class BDP_ModifierChatterbox : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "STCHAT";
		BDP_Modifier.DisplayName "Chatterbox";
		BDP_Modifier.Description "Doomguy says one liners automatically";
		BDP_Modifier.ModifierID Modifier_Chatterbox;
	}
	
	Override void worldthingdamaged(Worldevent e)
	{
		If(e.thing && e.thing.bisMonster && e.thing.health <= 0 && e.damagesource && e.damagesource is "BDP_PlayerPawn")
		{
			//console.printf(e.damagetype);
			//console.printf(e.damagesource.getclassname());
			 BDP_PlayerPawn BDPPlayer = BDP_PlayerPawn(e.damagesource);
			 If(e.damagetype == 'ExtremePunches')
			 {
				 If(BDPPlayer && !bdpplayer.tauntcooldown && random(1,3) > 1 )
				 {
					BDPPlayer.berserktaunt = true;
				 }
			 }
			 Else If(BDPPlayer && !bdpplayer.tauntcooldown && random(1,20) == 1)
			 {
				BDPPlayer.killtaunt = true;
				BDPPlayer.taunttimer = 15;
			 }
			
		}
		
	}


}

class BDP_ModifierTriathlon : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "TRIST00";
		BDP_Modifier.DisplayName "Triathlon";
		BDP_Modifier.Description "You can only carry 3 weapons at a time";
		BDP_Modifier.ModifierID Modifier_Triathlon;
	}
}



class BDP_ModifierOneUpmanship : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "BJBST00";
		BDP_Modifier.DisplayName "One-Upmanship";
		BDP_Modifier.Description "Soul Spheres grant extra lives";
		BDP_Modifier.ModifierID Modifier_OneUpmanship;
	}
}

class BDP_ModifierUltraNightmare : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "STFXDTH4";
		BDP_Modifier.DisplayName "Ultra Nightmare";
		BDP_Modifier.Description "Death is permanent. Good luck!";
		BDP_Modifier.ModifierID Modifier_UltraNightmare;
	}
}

class BDP_ModifierSkullCrusher : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "D4RST01";
		BDP_Modifier.DisplayName "Skullcrusher";
		BDP_Modifier.Description "HUD shows killstreaks";
		BDP_Modifier.ModifierID Modifier_SkullCrusher;
	}
	

	Override void worldthingdamaged(Worldevent e)
	{
		If(e.thing && e.thing.bisMonster && e.thing.health <= 0 && e.damagesource && e.damagesource is "BDP_PlayerPawn")
		{
			//console.printf(e.damagetype);
			//console.printf(e.damagesource.getclassname());
			 BDP_PlayerPawn BDPPlayer = BDP_PlayerPawn(e.damagesource);
			If(BDPPLAYER)
			{
				BDPPlayer.killstreak ++;
				BDPPlayer.killstreaktimer = 140;
			}
			 
			
		}
		
	}


}


class BDP_ModifierScoreMaster : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "STNERD";
		BDP_Modifier.DisplayName "Scoremaster";
		BDP_Modifier.Description "Gain points by killing monsters and collecting items\n\n 50k points grants an extra life";
		BDP_Modifier.ModifierID Modifier_ScoreMaster;
	}
	
	Override void worldthingdamaged(Worldevent e)
	{
		If(e.thing && e.thing.bisMonster && e.thing.health <= 0 && e.damagesource && e.damagesource is "BDP_PlayerPawn")
		{
			//console.printf(e.damagetype);
			//console.printf(e.damagesource.getclassname());
			 BDP_PlayerPawn BDPPlayer = BDP_PlayerPawn(e.damagesource);
			If(BDPPLAYER)
			{
				If(BDPPlayer.killstreak > 1)
				{
					double potentialscore = e.thing.getspawnhealth();
					double scoremodifier = (BDPPlayer.killstreak - 1);
					scoremodifier *= 0.1;
					scoremodifier += 1;
					potentialscore *= scoremodifier;
					//Console.printf("%d",potentialscore);
					BDPPlayer.score += potentialscore;
				}
				else
				{
					BDPPlayer.score += (e.thing.getspawnhealth());
				}
			}
			 
			
		}
		
	}


}

mixin class BDP_ScoreMixin
{
	int scoreAmount;
	property ScoreAmount : scoreAmount;
	
	int extraLives;
	property ExtraLives : extraLives;
	
	override bool TryPickup(in out Actor toucher)
	{
		if(super.TryPickup(toucher))
		{
			toucher.Score += scoreAmount;
			if(!extraLives) return true;
			BDP_PlayerPawn dplr = BDP_PlayerPawn(toucher);
			If(dplr && bdp_active_modifiers & Modifier_OneUpmanship)
				dplr.extralives += extraLives;
			return true;
		}
		return false;
	}
	
	override void PlayPickupSound(Actor toucher)
	{
		if(extraLives)
		{
			if(bdp_active_modifiers & Modifier_OneUpmanship) PickupSound = "1UP";
		}
		super.PlayPickupSound(toucher);
	}
}

class BDP_ModifierShockFactor : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "STSHOCK";
		BDP_Modifier.DisplayName "Shock Factor";
		BDP_Modifier.Description "Demons are hyper-aware of you";
		BDP_Modifier.ModifierID Modifier_ShockFactor;
	}
	
	Override void worldthingspawned(Worldevent e)
	{
		If(e.thing && e.thing.bismonster)
		{
			e.thing.bambush = false;
		}
	}
	
}


class BDP_ModifierPerfectHatred : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "FC0OUCH4";
		BDP_Modifier.DisplayName "Perfect Hatred";
		BDP_Modifier.Description "Demons are permanently enraged";
		BDP_Modifier.ModifierID Modifier_PerfectHatred;
	}
	
	Override void worldthingspawned(Worldevent e)
	{
		If(e.thing && e.thing.bismonster)
		{
			e.thing.MissileChanceMult *= 0.5;
			//e.thing.bmissileevenmore = true;
			e.thing.speed = (e.thing.speed * 1.5);
			e.thing.bnopain = true;
			e.thing.bnoinfighting = TRUE;
			e.thing.giveinventory("pissedarmor",1);
			//e.thing.A_giveinventory("thisreallypissesmeoff",(e.thing.health / 70));
		}
	}
	
}

class BDP_ModifierRealism : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "STREAL";
		BDP_Modifier.DisplayName "Realism";
		BDP_Modifier.Description "Player recieves 400% damage";
		BDP_Modifier.ModifierID Modifier_Realism;
	}
}



class BDP_ModifierGunslinger : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "CIGST10";
		BDP_Modifier.DisplayName "Gunslinger";
		BDP_Modifier.Description "Weapons deselected for 5 or more seconds instantly reload";
		BDP_Modifier.ModifierID Modifier_Gunslinger;
	}
}






class BDP_ModifierSequenceBreak : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "CYBST00";
		BDP_Modifier.DisplayName "Sequence Break";
		BDP_Modifier.Description "Doors can be kicked down whether you have the key or not.";
		BDP_Modifier.ModifierID Modifier_SequenceBreak;
	}
}

class BDP_ModifierFragger : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "STMAN";
		BDP_Modifier.DisplayName "Fragger";
		BDP_Modifier.Description "Start with frag grenades";
		BDP_Modifier.ModifierID Modifier_Fragger;
	}
}

class BDP_ModifierGluttony : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "MANST01";
		BDP_Modifier.DisplayName "Gluttony";
		BDP_Modifier.Description "Reloading discards the contents of the current magazine";
		BDP_Modifier.ModifierID Modifier_Gluttony;
	}
}

class BDP_ModifierKickintheHead : BDP_Modifier
{
	Default
	{
		BDP_Modifier.Icon "STKICK";
		BDP_Modifier.DisplayName "Kick In The Head";
		BDP_Modifier.Description "Recoil is affected by movement and will not auto-correct";
		BDP_Modifier.ModifierID Modifier_KickInTheHead;
	}
}