class BDP_ModifierSpawner : randomspawner
{
	Default
	{
		Dropitem "BDP_FraggerPickup";
		Dropitem "BDP_ShockFactorPickup";
		Dropitem "BDP_PerfectHatredPickup";
		Dropitem "BDP_GunSlingerPickup";
		Dropitem "BDP_OneUpmanshipPickup";
		Dropitem "BDP_UltraNightmarePickup";
		Dropitem "BDP_SequenceBreakPickup";
		Dropitem "BDP_SkullcrusherPickUp";
		Dropitem "BDP_ScoreMasterPickUp";
		Dropitem "BDP_RealismPickUp";
		Dropitem "BDP_GluttonyPickUp";
		Dropitem "BDP_KickintheHeadPickUp";
	}
}
class BDP_ModifierPickup : Inventory
{
	string modifierclass;
	property modifierclass : modifierclass;
	string modifiermessage;
	property modifiermessage : modifiermessage;
    Default
    {
        Inventory.MaxAmount 666;
		BDP_ModifierPickup.modifierclass "Modifier_Example2";
		Inventory.pickupsound "null";
		Inventory.pickupmessage "You got a Modifier!";
		BDP_ModifierPickup.modifiermessage "YOU SHOULDN'T BE SEEING THIS";
		+BRIGHT;
    }

    static void UnlockModifier(string modifierClass)
    {
      // This should be a Server CVar, so we should be able to use consoleplayer.
      let sv_unlockedmods = CVar.GetCVar("bdp_unlocked_modifiers", players[consoleplayer]);

      if(bdp_unlocked_modifiers == "") 
        sv_unlockedmods.SetString(modifierClass);
      else
        sv_unlockedmods.SetString(String.Format("%s, %s", bdp_unlocked_modifiers, modifierClass));
    }

    override void AttachToOwner(Actor other)
    {
        UnlockModifier(modifierclass);
		other.A_startsound("MODSTING",720,0,1.0,ATTN_NONE);
		other.A_Print(modifiermessage,5);
		EventHandler.SendNetworkEvent("flag_updatemodifierstatus");
        super.AttachToOwner(other);
		
    }
    
    States
    {
        Spawn:
            MODD A -1;
        stop;
    }
}

class BDP_FraggerPickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_Fragger";
		translation "200:207=[117,117,117]:[0,0,0]","240:247=244:247";
		BDP_ModifierPickup.modifiermessage "Fragger Unlocked!";
		+floatbob;
    }
}

class BDP_ShockFactorPickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_ShockFactor";
		translation "200:207=[236,0,0]:[81,0,0]","240:247=244:247";
		BDP_ModifierPickup.modifiermessage "Shock Factor Unlocked!";
		+floatbob;
    }
}

class BDP_PerfectHatredPickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_PerfectHatred";
		translation "200:207=[130,0,0]:[60,0,0]","240:247=244:247";
		BDP_ModifierPickup.modifiermessage "Perfect Hatred Unlocked!";
		+floatbob;
    }
}

class BDP_GunSlingerPickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_Gunslinger";
		translation "200:207=[79,149,0]:[0,77,81]","240:247=244:247";
		BDP_ModifierPickup.modifiermessage "Gunslinger Unlocked!";
		+floatbob;
    }
}

class BDP_OneUpmanshipPickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_OneUpmanship";
		translation "200:207=[19,210,149]:[0,51,51]","240:247=244:247";
		BDP_ModifierPickup.modifiermessage "One-Upmanship Unlocked!";
		+floatbob;
    }
}

class BDP_UltranightmarePickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_Ultranightmare";
		translation "200:207=[19,210,149]:[0,51,51]","240:247=244:247";
		BDP_ModifierPickup.modifiermessage "Ultra Nightmare Unlocked!";
		+floatbob;
    }
}

class BDP_SequenceBreakPickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_SequenceBreak";
		BDP_ModifierPickup.modifiermessage "Sequence Break Unlocked!";
		+floatbob;
    }
}

class BDP_ChatterboxPickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_Chatterbox";
		BDP_ModifierPickup.modifiermessage "Chatterbox Unlocked!";
		+floatbob;
    }
}

class BDP_TRIATHLONPickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_Triathlon";
		BDP_ModifierPickup.modifiermessage "Triathlon Unlocked!";
		+floatbob;
    }
}

class BDP_SkullcrusherPickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_Skullcrusher";
		BDP_ModifierPickup.modifiermessage "Skullcrusher Unlocked!";
		+floatbob;
    }
}

class BDP_ScoremasterPickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_Scoremaster";
		BDP_ModifierPickup.modifiermessage "Scoremaster Unlocked!";
		+floatbob;
    }
}

class BDP_RealismPickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_Realism";
		BDP_ModifierPickup.modifiermessage "Realism Unlocked!";
		+floatbob;
    }
}

class BDP_GluttonyPickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_Gluttony";
		BDP_ModifierPickup.modifiermessage "Gluttony Unlocked!";
		+floatbob;
    }
}


class BDP_KickInTheHeadPickup : BDP_ModifierPickup
{
 Default
    {
        
		BDP_ModifierPickup.modifierclass "Modifier_KickintheHead";
		BDP_ModifierPickup.modifiermessage "Kick In The Head Unlocked!";
		+floatbob;
    }
}

//Man And A Half "200:207=[117,117,117]:[0,0,0]"